# trusttunnel 子模块
AddPreviewTest(TrusttunnelDgramSession.cpp)
target_link_libraries(TrusttunnelDgramSession PRIVATE PreviewTransport PreviewProtocolTrusttunnel PreviewTestSupport)

AddPreviewTest(TrusttunnelCodecDeep.cpp)
target_link_libraries(TrusttunnelCodecDeep PRIVATE PreviewProtocolTrusttunnel PreviewTestSupport)
