# shadowtls 子模块
AddPreviewTest(ShadowtlsConnSession.cpp)
target_link_libraries(ShadowtlsConnSession PRIVATE PreviewTransport PreviewProtocolShadowtls PreviewTestSupport)

AddPreviewTest(ShadowtlsCodecDeep.cpp)
target_link_libraries(ShadowtlsCodecDeep PRIVATE PreviewProtocolShadowtls PreviewTestSupport)
