# misc 子模块
AddPreviewTest(StealthVmessErrorCoverage.cpp)
target_link_libraries(StealthVmessErrorCoverage PRIVATE PreviewTransport PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolReality PreviewProtocolRestls PreviewProtocolShadowtls PreviewProtocolTrusttunnel PreviewProtocolVmess PreviewProtocolWs PreviewTestSupport)
target_compile_options(StealthVmessErrorCoverage PRIVATE -O0 -fno-inline)

# misc 子模块
AddPreviewTest(StealthMuxBeastTest.cpp)
target_link_libraries(StealthMuxBeastTest PRIVATE PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolMux PreviewProtocolReality PreviewProtocolRestls PreviewProtocolShadowtls PreviewProtocolTrusttunnel PreviewProtocolWs PreviewTestSupport)

# misc 子模块
AddPreviewTest(ConnDecoratorDeep.cpp)
target_link_libraries(ConnDecoratorDeep PRIVATE PreviewTransport PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolMux PreviewProtocolReality PreviewProtocolTuic PreviewTestSupport)
target_compile_options(ConnDecoratorDeep PRIVATE -O0 -fno-inline)
