# vless 子模块测试
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(VlessClientServerPerf.cpp)
 target_link_libraries(VlessClientServerPerf PRIVATE PreviewTransport PreviewProtocolVless PreviewTestSupport)
endif()
AddPreviewTest(VlessConnErrorMatrix.cpp)
target_link_libraries(VlessConnErrorMatrix PRIVATE PreviewTransport PreviewProtocolVless PreviewTestSupport)
AddPreviewTest(VlessConnSession.cpp)
target_link_libraries(VlessConnSession PRIVATE PreviewTransport PreviewProtocolVless PreviewTestSupport)
if(PRISM_ENABLE_STRESS)
    AddPreviewTest(VlessStressTest.cpp)
 target_link_libraries(VlessStressTest PRIVATE PreviewTransport PreviewProtocolVless PreviewTestSupport)
endif()
