# vless 子模块测试
prism_add_test(VlessClientServerPerf.cpp)
target_link_libraries(VlessClientServerPerf PRIVATE vmtest_common)
prism_add_test(VlessConnErrorMatrix.cpp)
target_link_libraries(VlessConnErrorMatrix PRIVATE vmtest_common)
prism_add_test(VlessConnSession.cpp)
target_link_libraries(VlessConnSession PRIVATE vmtest_common)
prism_add_test(VlessStressTest.cpp)
target_link_libraries(VlessStressTest PRIVATE vmtest_common)
