# recognition 子模块测试
AddPreviewTest(RecognitionTest.cpp)
target_link_libraries(RecognitionTest PRIVATE PreviewFoundation PreviewTransport PreviewRuntime PreviewTestSupport)
AddProductionTest(TlsRecord.cpp)
target_link_libraries(TlsRecord PRIVATE ProductionTestSupport)
AddProductionTest(TlsSignal.cpp)
target_link_libraries(TlsSignal PRIVATE ProductionTestSupport)
AddPreviewTest(SchemeExecutorTest.cpp)
target_link_libraries(SchemeExecutorTest PRIVATE PreviewTransport PreviewRuntime PreviewTestSupport)
