prism_add_test(VmessAuth.cpp)
prism_add_test(VmessKdf.cpp)
prism_add_test(VmessHeader.cpp)
prism_add_test(VmessChunk.cpp)
prism_add_test(VmessConnEcho.cpp)
prism_add_test(VmessBeastTest.cpp)
prism_add_test(VmessClientServerPerf.cpp)
target_link_libraries(VmessBeastTest PRIVATE vmtest_common)
target_link_libraries(VmessClientServerPerf PRIVATE vmtest_common)
