# transport 子模块测试
prism_add_test(CoreTransmission.cpp)
target_link_libraries(CoreTransmission PRIVATE vmtest_common)
prism_add_test(EncryptedTest.cpp)
target_link_libraries(EncryptedTest PRIVATE vmtest_common)
prism_add_test(PreviewDeep.cpp)
target_link_libraries(PreviewDeep PRIVATE vmtest_common)
prism_add_test(PreviewTransmissionTest.cpp)
target_link_libraries(PreviewTransmissionTest PRIVATE vmtest_common)
prism_add_test(TestPsmTransport.cpp)
target_link_libraries(TestPsmTransport PRIVATE vmtest_common)
prism_add_test(TransportDecoratorCoverage.cpp)
target_link_libraries(TransportDecoratorCoverage PRIVATE vmtest_common)
prism_add_test(TransportTest.cpp)
target_link_libraries(TransportTest PRIVATE vmtest_common)
target_compile_options(TestPsmTransport PRIVATE -O0 -fno-inline)
target_compile_options(TransportDecoratorCoverage PRIVATE -O0 -fno-inline)
