# fault 子模块测试
prism_add_test(CoreError.cpp)
target_link_libraries(CoreError PRIVATE vmtest_common)
prism_add_test(CoreFault.cpp)
target_link_libraries(CoreFault PRIVATE vmtest_common)
prism_add_test(FaultCoverage.cpp)
target_link_libraries(FaultCoverage PRIVATE vmtest_common)
prism_add_test(PreviewErrorTest.cpp)
target_link_libraries(PreviewErrorTest PRIVATE vmtest_common)
prism_add_test(PreviewFaultTest.cpp)
target_link_libraries(PreviewFaultTest PRIVATE vmtest_common)
