# fault 子模块测试
AddPreviewTest(CoreError.cpp)
target_link_libraries(CoreError PRIVATE PreviewFoundation PreviewTestSupport)
AddPreviewTest(CoreFault.cpp)
target_link_libraries(CoreFault PRIVATE PreviewFoundation PreviewTestSupport)
AddPreviewTest(FaultCoverage.cpp)
target_link_libraries(FaultCoverage PRIVATE PreviewFoundation PreviewTestSupport)
AddPreviewTest(PreviewErrorTest.cpp)
target_link_libraries(PreviewErrorTest PRIVATE PreviewFoundation PreviewTestSupport)
AddPreviewTest(PreviewFaultTest.cpp)
target_link_libraries(PreviewFaultTest PRIVATE PreviewFoundation PreviewTestSupport)
