prism_add_test(Shadowsocks.cpp)
prism_add_test(ShadowsocksConnPure.cpp)
prism_add_test(ShadowsocksDatagram.cpp)
prism_add_test(ShadowsocksDatagramPure.cpp)
prism_add_test(ShadowsocksDatagramDeep.cpp)
prism_add_test(ShadowsocksFramingPure.cpp)
prism_add_test(ShadowsocksProcessPure.cpp)
prism_add_test(Ss2022ClientServerPerf.cpp)
prism_add_test(Shadowsocks2022BeastTest.cpp)
target_link_libraries(Shadowsocks2022BeastTest PRIVATE vmtest_common)
