# socks5 子模块测试
AddPreviewTest(Socks5BeastTest.cpp)
target_link_libraries(Socks5BeastTest PRIVATE PreviewProtocolSocks5 PreviewTestSupport)
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(Socks5ClientServerPerf.cpp)
 target_link_libraries(Socks5ClientServerPerf PRIVATE PreviewTransport PreviewProtocolSocks5 PreviewTestSupport)
endif()
AddPreviewTest(Socks5ConnErrorMatrix.cpp)
target_link_libraries(Socks5ConnErrorMatrix PRIVATE PreviewTransport PreviewProtocolSocks5 PreviewTestSupport)
AddPreviewTest(Socks5ConnSession.cpp)
target_link_libraries(Socks5ConnSession PRIVATE PreviewTransport PreviewProtocolSocks5 PreviewTestSupport)
AddPreviewTest(Socks5DgramSession.cpp)
target_link_libraries(Socks5DgramSession PRIVATE PreviewTransport PreviewProtocolSocks5 PreviewTestSupport)
if(PRISM_ENABLE_STRESS)
    AddPreviewTest(Socks5StressTest.cpp)
 target_link_libraries(Socks5StressTest PRIVATE PreviewTransport PreviewProtocolSocks5 PreviewTestSupport)
endif()
