AddProductionTest(H2muxCraftDeep.cpp)
target_link_libraries(H2muxCraftDeep PRIVATE ProductionTestSupport)

AddPreviewTest(H2muxFrameError.cpp)
target_link_libraries(H2muxFrameError PRIVATE PreviewProtocolMux PreviewTestSupport)

AddProductionTest(H2muxCraftAsync.cpp)
target_link_libraries(H2muxCraftAsync PRIVATE ProductionTestSupport)

AddProductionTest(H2muxCraftDeep2.cpp)
target_link_libraries(H2muxCraftDeep2 PRIVATE ProductionTestSupport)
