/**
 * @file RealityResponseDeep.cpp
 * @brief Reality response 深度测试
 * @details 测试 response.cpp 中匿名命名空间的纯函数：
 *          make_handshake_message、build_server_hello_body、
 *          build_encrypted_extensions、generate_reality_certificate、
 *          build_certificate、build_certificate_verify。
 *          以及 encrypt_record 边缘分支。
 *          通过 #include 源文件覆盖编译行。
 */

#include <gtest/gtest.h>

#include <prism/core/core.hpp>

// #include 源文件增加覆盖率计数
#include "../../src/prism/stealth/facade/reality/util/response.cpp"

namespace
{
    using namespace psm::stealth::reality;
    namespace tls = psm::protocol::tls;
    using psm::crypto::ed25519_keypair;

    // ─── make_handshake_message ──────────────────────

    TEST(RealityResponseDeep, MakeHandshakeMessageEmpty)
    {
        auto msg = make_handshake_message(0x01, {});
        // 1 byte type + 3 bytes length(0) = 4 bytes
        EXPECT_TRUE(msg.size() == 4) << "make_hs_msg empty: size=4";
        EXPECT_TRUE(msg[0] == 0x01) << "make_hs_msg empty: type=0x01";
        EXPECT_TRUE(msg[1] == 0x00 && msg[2] == 0x00 && msg[3] == 0x00)
                     << "make_hs_msg empty: length=0";
    }

    TEST(RealityResponseDeep, MakeHandshakeMessageWithBody)
    {
        const std::uint8_t body[] = {0xAA, 0xBB, 0xCC, 0xDD};
        auto msg = make_handshake_message(0x02, body);
        EXPECT_TRUE(msg.size() == 8) << "make_hs_msg body: size=8";
        EXPECT_TRUE(msg[0] == 0x02) << "make_hs_msg body: type=0x02";
        EXPECT_TRUE(msg[1] == 0x00 && msg[2] == 0x00 && msg[3] == 0x04)
                     << "make_hs_msg body: length=4";
        EXPECT_TRUE(msg[4] == 0xAA) << "make_hs_msg body: data[0]";
        EXPECT_TRUE(msg[7] == 0xDD) << "make_hs_msg body: data[3]";
    }

    TEST(RealityResponseDeep, MakeHandshakeMessageLargeBody)
    {
        std::array<std::uint8_t, 256> body{};
        body[0] = 0x42;
        body[255] = 0xFF;
        auto msg = make_handshake_message(tls::HS_SERVER_HELLO, body);
        EXPECT_TRUE(msg.size() == 4 + 256) << "make_hs_msg large: size=260";
        EXPECT_TRUE(msg[0] == tls::HS_SERVER_HELLO) << "make_hs_msg large: type=SH";
        // length = 256 = 0x000100
        EXPECT_TRUE(msg[1] == 0x00 && msg[2] == 0x01 && msg[3] == 0x00)
                     << "make_hs_msg large: length=256";
    }

    TEST(RealityResponseDeep, MakeHandshakeMessageDifferentTypes)
    {
        auto m1 = make_handshake_message(tls::HS_ENCRYPTED_EXTENSIONS, {});
        EXPECT_TRUE(m1[0] == tls::HS_ENCRYPTED_EXTENSIONS) << "make_hs_msg types: EE";

        auto m2 = make_handshake_message(tls::HS_CERTIFICATE, {});
        EXPECT_TRUE(m2[0] == tls::HS_CERTIFICATE) << "make_hs_msg types: Cert";

        auto m3 = make_handshake_message(tls::HS_CERTIFICATE_VERIFY, {});
        EXPECT_TRUE(m3[0] == tls::HS_CERTIFICATE_VERIFY) << "make_hs_msg types: CV";

        auto m4 = make_handshake_message(tls::HS_FINISHED, {});
        EXPECT_TRUE(m4[0] == tls::HS_FINISHED) << "make_hs_msg types: Finished";
    }

    // ─── build_encrypted_extensions ──────────────────

    TEST(RealityResponseDeep, BuildEncryptedExtensions)
    {
        auto ee = build_encrypted_extensions();
        EXPECT_TRUE(ee.size() == 2) << "build_ee: size=2";
        EXPECT_TRUE(ee[0] == 0x00 && ee[1] == 0x00) << "build_ee: extensions_length=0";
    }

    // ─── build_server_hello_body ─────────────────────

    TEST(RealityResponseDeep, BuildShVersionAndRandom)
    {
        tls::hello_features ch;
        ch.session_id.clear();

        std::array<std::uint8_t, 32> eph_pub{};
        auto body = build_server_hello_body(ch, eph_pub);

        // Version TLS 1.2 at offset 0
        EXPECT_TRUE(body[0] == 0x03 && body[1] == 0x03) << "build_sh: version=0x0303";
        // Random at offset 2..33 (32 bytes, generated by RAND_bytes)
        // Just verify it's present (body.size > 34)
        EXPECT_TRUE(body.size() > 34) << "build_sh: body > 34 bytes (has random)";
    }

    TEST(RealityResponseDeep, BuildShSessionIdEcho)
    {
        tls::hello_features ch;
        ch.session_id = {0x01, 0x02, 0x03, 0x04};

        std::array<std::uint8_t, 32> eph_pub{};
        auto body = build_server_hello_body(ch, eph_pub);

        // session_id_len at offset 34
        EXPECT_TRUE(body[34] == 4) << "build_sh sid: len=4";
        // session_id at offset 35..38
        EXPECT_TRUE(body[35] == 0x01) << "build_sh sid: byte[0]";
        EXPECT_TRUE(body[38] == 0x04) << "build_sh sid: byte[3]";
    }

    TEST(RealityResponseDeep, BuildShEmptySessionId)
    {
        tls::hello_features ch;
        ch.session_id.clear();

        std::array<std::uint8_t, 32> eph_pub{};
        auto body = build_server_hello_body(ch, eph_pub);

        EXPECT_TRUE(body[34] == 0) << "build_sh empty sid: len=0";
        // cipher_suite at offset 35 (no sid bytes)
        const auto cipher = (static_cast<std::uint16_t>(body[35]) << 8) | body[36];
        EXPECT_TRUE(cipher == tls::CIPHER_AES_128_GCM_SHA256) << "build_sh empty sid: cipher=0x1301";
    }

    TEST(RealityResponseDeep, BuildShFullSessionId)
    {
        tls::hello_features ch;
        ch.session_id.assign(32, 0x42);

        std::array<std::uint8_t, 32> eph_pub{};
        auto body = build_server_hello_body(ch, eph_pub);

        EXPECT_TRUE(body[34] == 32) << "build_sh full sid: len=32";
        EXPECT_TRUE(body[35] == 0x42) << "build_sh full sid: first byte";
        EXPECT_TRUE(body[66] == 0x42) << "build_sh full sid: last byte";
    }

    TEST(RealityResponseDeep, BuildShCipherAndCompression)
    {
        tls::hello_features ch;
        ch.session_id.clear();

        std::array<std::uint8_t, 32> eph_pub{};
        auto body = build_server_hello_body(ch, eph_pub);

        // Offset after version(2)+random(32)+sid_len(1)+sid(0)=35
        // cipher at 35,36; compression at 37
        const auto cipher = (static_cast<std::uint16_t>(body[35]) << 8) | body[36];
        EXPECT_TRUE(cipher == tls::CIPHER_AES_128_GCM_SHA256) << "build_sh: cipher=0x1301";
        EXPECT_TRUE(body[37] == 0x00) << "build_sh: compression=0";
    }

    TEST(RealityResponseDeep, BuildShExtensions)
    {
        tls::hello_features ch;
        ch.session_id.clear();

        std::array<std::uint8_t, 32> eph_pub{};
        for (std::size_t i = 0; i < 32; ++i)
            eph_pub[i] = static_cast<std::uint8_t>(i);

        auto body = build_server_hello_body(ch, eph_pub);

        // extensions_length at offset 38 (no sid)
        const auto ext_len = (static_cast<std::uint16_t>(body[38]) << 8) | body[39];
        EXPECT_TRUE(ext_len > 0) << "build_sh ext: len > 0";

        // supported_versions ext: type 0x002B at offset 40
        const auto ext_type1 = (static_cast<std::uint16_t>(body[40]) << 8) | body[41];
        EXPECT_TRUE(ext_type1 == tls::EXT_SUPPORTED_VERSIONS) << "build_sh ext: supported_versions";

        // key_share ext: type 0x0033 after supported_versions
        // supported_versions: type(2) + len(2) + data(2) = 6 bytes
        const auto ext_type2 = (static_cast<std::uint16_t>(body[46]) << 8) | body[47];
        EXPECT_TRUE(ext_type2 == tls::EXT_KEY_SHARE) << "build_sh ext: key_share";

        // key_share should contain eph_pub
        // key_share ext: type(2) + len(2) + group(2) + key_len(2) + key(32)
        // supported_versions ends at 45, key_share type at 46-47, ext_len at 48-49
        // ext body starts at 50: group(50-51), key_len(52-53), key_data(54+)
        const auto group = (static_cast<std::uint16_t>(body[50]) << 8) | body[51];
        EXPECT_TRUE(group == tls::GROUP_X25519) << "build_sh ext: group=X25519";
        const auto key_len = (static_cast<std::uint16_t>(body[52]) << 8) | body[53];
        EXPECT_TRUE(key_len == 32) << "build_sh ext: key_len=32";
        EXPECT_TRUE(body[54] == 0x00) << "build_sh ext: eph_pub[0]";
        EXPECT_TRUE(body[85] == 0x1F) << "build_sh ext: eph_pub[31]";
    }

    // ─── generate_reality_certificate ────────────────

    TEST(RealityResponseDeep, GenCertInvalidKeyLen)
    {
        std::array<std::uint8_t, 16> short_key{};
        auto [cert_der, kp] = generate_reality_certificate(short_key);
        EXPECT_TRUE(cert_der.empty()) << "gen_cert: short key -> empty cert";
    }

    TEST(RealityResponseDeep, GenCertZeroKey)
    {
        std::array<std::uint8_t, 32> auth_key{};
        auto [cert_der, kp] = generate_reality_certificate(auth_key);
        EXPECT_TRUE(!cert_der.empty()) << "gen_cert zero: non-empty cert";
        EXPECT_TRUE(cert_der[0] == 0x30) << "gen_cert zero: DER SEQUENCE tag";
        EXPECT_TRUE(cert_der.size() > 100) << "gen_cert zero: > 100 bytes";

        bool pub_all_zero = true;
        for (auto b : kp.public_key)
            if (b != 0) pub_all_zero = false;
        EXPECT_TRUE(!pub_all_zero) << "gen_cert zero: public key non-zero";
    }

    TEST(RealityResponseDeep, GenCertDeterministicStructure)
    {
        std::array<std::uint8_t, 32> auth_key{};
        for (std::size_t i = 0; i < 32; ++i)
            auth_key[i] = static_cast<std::uint8_t>(i + 1);

        auto [cert1, kp1] = generate_reality_certificate(auth_key);
        auto [cert2, kp2] = generate_reality_certificate(auth_key);

        EXPECT_TRUE(!cert1.empty()) << "gen_cert det: cert1 non-empty";
        EXPECT_TRUE(!cert2.empty()) << "gen_cert det: cert2 non-empty";
        // Same auth_key but different Ed25519 keypair → different cert content
        // Public keys differ (randomly generated)
        EXPECT_TRUE(kp1.public_key != kp2.public_key)
                     << "gen_cert det: different keypairs per call";
    }

    TEST(RealityResponseDeep, GenCertDifferentAuthKeys)
    {
        std::array<std::uint8_t, 32> key1{};
        for (std::size_t i = 0; i < 32; ++i)
            key1[i] = static_cast<std::uint8_t>(i);
        std::array<std::uint8_t, 32> key2{};
        for (std::size_t i = 0; i < 32; ++i)
            key2[i] = static_cast<std::uint8_t>(i + 0x80);

        auto [cert1, kp1] = generate_reality_certificate(key1);
        auto [cert2, kp2] = generate_reality_certificate(key2);

        EXPECT_TRUE(!cert1.empty() && !cert2.empty()) << "gen_cert diff: both non-empty";
        // Certs differ (different HMAC signature at minimum)
        // Even if keypairs happen to differ, the HMAC-signed cert will differ
    }

    // ─── build_certificate ───────────────────────────

    TEST(RealityResponseDeep, BuildCertNoAuthKey)
    {
        const std::uint8_t dest_cert[] = {0x30, 0x82, 0x01, 0x00, 0x04};
        psm::crypto::ed25519_keypair out_kp{};

        auto body = build_certificate(dest_cert, {}, out_kp);
        EXPECT_TRUE(!body.empty()) << "build_cert noauth: non-empty";
        EXPECT_TRUE(body[0] == 0x00) << "build_cert noauth: request_context=0";

        // Verify dest_cert is embedded: after request_ctx(1) + cert_list_len(3) +
        // cert_len(3) + cert_data + extensions_len(2)
        // Total overhead = 1 + 3 + 3 + 2 = 9 bytes
        EXPECT_TRUE(body.size() == 9 + sizeof(dest_cert))
                     << "build_cert noauth: correct total size";
    }

    TEST(RealityResponseDeep, BuildCertWithAuthKey)
    {
        const std::uint8_t dest_cert[] = {0x30, 0x01, 0x02};
        std::array<std::uint8_t, 32> auth_key{};
        for (std::size_t i = 0; i < 32; ++i)
            auth_key[i] = static_cast<std::uint8_t>(i + 1);

        psm::crypto::ed25519_keypair out_kp{};

        auto body = build_certificate(dest_cert, auth_key, out_kp);
        EXPECT_TRUE(!body.empty()) << "build_cert auth: non-empty";
        EXPECT_TRUE(body[0] == 0x00) << "build_cert auth: request_context=0";

        // out_kp should be populated by generate_reality_certificate
        bool pub_zero = true;
        for (auto b : out_kp.public_key)
            if (b != 0) pub_zero = false;
        EXPECT_TRUE(!pub_zero) << "build_cert auth: out_kp public key set";
    }

    TEST(RealityResponseDeep, BuildCertEmptyDestNoAuth)
    {
        // Empty auth_key and empty dest_cert → empty cert_der inside
        psm::crypto::ed25519_keypair out_kp{};
        auto body = build_certificate({}, {}, out_kp);
        // Still builds the envelope, just with empty cert_der
        EXPECT_TRUE(!body.empty()) << "build_cert empty: body still non-empty (envelope)";
        EXPECT_TRUE(body[0] == 0x00) << "build_cert empty: request_context=0";
    }

    // ─── build_certificate_verify ────────────────────

    TEST(RealityResponseDeep, BuildCertVerifyStructure)
    {
        psm::crypto::ed25519_keypair kp{};
        ED25519_keypair(kp.public_key.data(), kp.private_key.data());

        std::array<std::uint8_t, 32> transcript{};
        for (std::size_t i = 0; i < 32; ++i)
            transcript[i] = static_cast<std::uint8_t>(i);

        auto body = build_certificate_verify(kp, transcript);
        // sig_scheme(2) + sig_len(2) + signature(64) = 68
        EXPECT_TRUE(body.size() == 68) << "build_cv: size=68";
        // SIG_ED25519 = 0x0807
        EXPECT_TRUE(body[0] == 0x08 && body[1] == 0x07) << "build_cv: scheme=0x0807";
        // sig_len = 64 = 0x0040
        EXPECT_TRUE(body[2] == 0x00 && body[3] == 0x40) << "build_cv: sig_len=64";
    }

    TEST(RealityResponseDeep, BuildCertVerifyEmptyTranscript)
    {
        psm::crypto::ed25519_keypair kp{};
        ED25519_keypair(kp.public_key.data(), kp.private_key.data());

        std::array<std::uint8_t, 32> transcript{};
        auto body = build_certificate_verify(kp, transcript);
        EXPECT_TRUE(body.size() == 68) << "build_cv empty: size=68";
    }

    TEST(RealityResponseDeep, BuildCertVerifyDifferentKeys)
    {
        psm::crypto::ed25519_keypair kp1{}, kp2{};
        ED25519_keypair(kp1.public_key.data(), kp1.private_key.data());
        ED25519_keypair(kp2.public_key.data(), kp2.private_key.data());

        std::array<std::uint8_t, 32> transcript{};
        for (std::size_t i = 0; i < 32; ++i)
            transcript[i] = static_cast<std::uint8_t>(i);

        auto body1 = build_certificate_verify(kp1, transcript);
        auto body2 = build_certificate_verify(kp2, transcript);

        EXPECT_TRUE(body1.size() == 68 && body2.size() == 68) << "build_cv diff: both size=68";
        EXPECT_TRUE(body1 != body2) << "build_cv diff: different keys -> different sig";
    }

    TEST(RealityResponseDeep, BuildCertVerifyDifferentTranscript)
    {
        psm::crypto::ed25519_keypair kp{};
        ED25519_keypair(kp.public_key.data(), kp.private_key.data());

        std::array<std::uint8_t, 32> t1{};
        t1[0] = 0x01;
        std::array<std::uint8_t, 32> t2{};
        t2[0] = 0x02;

        auto body1 = build_certificate_verify(kp, t1);
        auto body2 = build_certificate_verify(kp, t2);

        EXPECT_TRUE(body1 != body2) << "build_cv transcript: different transcript -> different sig";
    }

    // ─── encrypt_record 完整往返 ────────────────────

    TEST(RealityResponseDeep, EncryptDecryptRoundtrip)
    {
        // 加密后再解密，验证往返正确性
        std::array<std::uint8_t, 16> key{};
        for (std::size_t i = 0; i < 16; ++i)
            key[i] = static_cast<std::uint8_t>(i + 1);
        std::array<std::uint8_t, 12> iv{};
        for (std::size_t i = 0; i < 12; ++i)
            iv[i] = static_cast<std::uint8_t>(i + 1);

        const std::uint8_t plaintext[] = {0xDE, 0xAD, 0xBE, 0xEF};

        encrypt_params params{key, iv, 0, tls::CT_HANDSHAKE, plaintext};
        auto [ec, encrypted] = encrypt_record(params);
        EXPECT_TRUE(ec == psm::fault::code::success) << "encrypt roundtrip: success";

        // 手动解密验证
        // encrypted = record_header(5) + ciphertext_with_tag
        const auto enc_payload_len = encrypted.size() - 5;
        // inner = plaintext + content_type + tag
        // so plaintext.size() + 1 + 16 = enc_payload_len
        EXPECT_TRUE(enc_payload_len == sizeof(plaintext) + 1 + 16)
                     << "encrypt roundtrip: payload len correct";

        // 用 AEAD open 解密
        auto nonce = psm::stealth::common::aead_nonce(iv, 0);
        auto ad = psm::stealth::common::record_ad(static_cast<std::uint16_t>(enc_payload_len));

        psm::crypto::aead_context aead(psm::crypto::aead_cipher::aes_128_gcm, key);
        psm::memory::vector<std::uint8_t> decrypted(sizeof(plaintext) + 1);

        auto open_ec = aead.open(psm::crypto::open_input{
            decrypted,
            std::span<const std::uint8_t>(encrypted.data() + 5, enc_payload_len),
            std::span<const std::uint8_t>{nonce.data(), nonce.size()},
            std::span<const std::uint8_t>{ad.data(), ad.size()}});

        EXPECT_TRUE(!psm::fault::failed(open_ec)) << "encrypt roundtrip: decrypt success";
        EXPECT_TRUE(decrypted.size() == sizeof(plaintext) + 1) << "encrypt roundtrip: decrypted size";
        // 明文部分
        EXPECT_TRUE(decrypted[0] == 0xDE) << "encrypt roundtrip: plaintext[0]";
        EXPECT_TRUE(decrypted[3] == 0xEF) << "encrypt roundtrip: plaintext[3]";
        // content_type 尾部
        EXPECT_TRUE(decrypted[4] == tls::CT_HANDSHAKE) << "encrypt roundtrip: trailing content_type";
    }

} // namespace
