# shadowsocks2022 子模块测试
prism_add_test(Shadowsocks2022BeastTest.cpp)
target_link_libraries(Shadowsocks2022BeastTest PRIVATE vmtest_common)
prism_add_test(Ss2022ClientServerPerf.cpp)
target_link_libraries(Ss2022ClientServerPerf PRIVATE vmtest_common)
prism_add_test(Ss2022CodecDeep.cpp)
target_link_libraries(Ss2022CodecDeep PRIVATE vmtest_common)
prism_add_test(Ss2022ConnErrorMatrix.cpp)
target_link_libraries(Ss2022ConnErrorMatrix PRIVATE vmtest_common)
target_compile_options(Ss2022CodecDeep PRIVATE -O0 -fno-inline)
prism_add_test(Ss2022DgramSession.cpp)
target_link_libraries(Ss2022DgramSession PRIVATE vmtest_common)
