# tuic 子模块测试
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(TuicClientServerPerf.cpp)
    target_link_libraries(TuicClientServerPerf PRIVATE PreviewTransport PreviewProtocolTuic PreviewTestSupport)
endif()
AddPreviewTest(TuicConnErrorMatrix.cpp)
target_link_libraries(TuicConnErrorMatrix PRIVATE PreviewTransport PreviewProtocolTuic PreviewTestSupport)
AddPreviewTest(TuicDgramDeep.cpp)
target_link_libraries(TuicDgramDeep PRIVATE PreviewTransport PreviewProtocolTuic PreviewTestSupport)
AddPreviewTest(TuicConnSession.cpp)
target_link_libraries(TuicConnSession PRIVATE PreviewTransport PreviewProtocolTuic PreviewTestSupport)
