# nested 子模块
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(StealthNestedPerf3.cpp)
 target_link_libraries(StealthNestedPerf3 PRIVATE PreviewTransport PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolReality PreviewProtocolRestls PreviewProtocolShadowtls PreviewProtocolSocks5 PreviewProtocolTrojan PreviewProtocolTrusttunnel PreviewProtocolVless PreviewProtocolWs PreviewTestSupport)
endif()

# nested 子模块
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(StealthNestedPerf2.cpp)
 target_link_libraries(StealthNestedPerf2 PRIVATE PreviewTransport PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolReality PreviewProtocolRestls PreviewProtocolShadowtls PreviewProtocolSocks5 PreviewProtocolTrojan PreviewProtocolTrusttunnel PreviewProtocolVless PreviewProtocolWs PreviewTestSupport)
endif()

# nested 子模块
if(PRISM_ENABLE_BENCHMARK)
    AddPreviewTest(StealthNestedPerf.cpp)
 target_link_libraries(StealthNestedPerf PRIVATE PreviewTransport PreviewProtocolAnytls PreviewProtocolGun PreviewProtocolReality PreviewProtocolRestls PreviewProtocolShadowtls PreviewProtocolSocks5 PreviewProtocolTrojan PreviewProtocolTrusttunnel PreviewProtocolVless PreviewProtocolWs PreviewTestSupport)
endif()
